    dataset_name: 'products'
    inference: True
    LBMB_val: False
    mode: 'clustergcn'
    ppr_params:
            neighbor_topk: 40
            merge_max_size: null
            primes_per_batch: 4500
            alpha: 0.25
            eps: 5.e-4
    batch_params:
            num_batches: [ 32, 8, 8]
            part_topk: [ 1, 1 ]
            alpha: 0.25
    micro_batch: 1
    batch_size: 1
    batch_order: 'rand'
    small_trainingset: 1

    graphmodel: 'sage'
    hidden_channels: 256
    reg: 0.
    num_layers: 3
    sprs: 1
    sprs_rate: 1
    sprs_method: 'LSIM'
