    dataset_name: 'arxiv'
    inference: True
    LBMB_val: False
    mode: 'rw_sampling'
    ppr_params:
            neighbor_topk: 16
            merge_max_size: null
            primes_per_batch: 9000
            alpha: 0.25
            eps: 2.e-4
    batch_params:
            num_batches: [ 8, 2, 2 ]
            part_topk: [ 1, 1 ]
            alpha: 0.25
    rw_sampling_params:
        batch_size: [48000, 24000]
        num_steps: 2
        walk_length: 2
        sample_coverage: 100
    micro_batch: 1
    batch_size: 1
    batch_order: 'rand'
    small_trainingset: 1

    graphmodel: 'sage'
    hidden_channels: 256
    reg: 0.
    num_layers: 3
    sprs: 2
    sprs_rate: 0.8
    sprs_method: 'LSIM'
